[[pages]]
path = "PropertyAnalysis.py"
name = "Datasets Analysis"
icon = ":bookmark_tabs:"

[[pages]]
path = "MolVisualization.py"
name = "Molcule Visualization"
icon = ":eye-in-speech-bubble:"

[[pages]]
path = "MolComparison.py"
name = "Molcule Comparison"
icon = ":eye-in-speech-bubble:"
